name: valor-pro-action-bash-test
description: valor-pro-action-bash-test.
author: valor-pro 
branding:
  icon: 'thumbs-up'
  color: 'white'

inputs:
  kube_config:
    description: 'Username used to log against the Docker registry'
    required: true
    
runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash 
    - run: script.sh
      shell: bash
      env:
        KUBE_CONFIG: ${{ inputs.kube_config }}